version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: ehr-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ehr_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ehr-network

  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ehr-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/ehr_db?authSource=admin
      JWT_SECRET: your-secret-key-change-in-production-12345
      FABRIC_NETWORK_PATH: /app/server/fabric/network-config.yaml
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./server:/app/server
      - ./shared:/app/shared
    depends_on:
      - mongodb
    networks:
      - ehr-network

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ehr-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ehr-network

networks:
  ehr-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
