import { Gateway, Wallets, Wallet, GatewayOptions, Contract, type Identity, type X509Identity } from 'fabric-network';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto'; // Added for hashing
import { fileURLToPath } from 'url';

// --- Configuration ---
// These paths are relative to this file (server/fabric/blockchain.ts)

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const USE_FABRIC = process.env.USE_FABRIC?.trim().toLowerCase() === 'true';

if (!USE_FABRIC) {
  console.warn('USE_FABRIC is disabled. Running in database-only mode without Hyperledger Fabric.');
}

/**
 * Path to the file system wallet that holds the identities (Admin, appUser).
 * This assumes a 'wallet' directory at the 'server' level.
 * (e.g., /EHR/server/wallet)
 */
const WALLET_PATH = path.resolve(__dirname, '..', 'wallet');

/**
 * Path to the connection profile for Org1.
 * This file is generated by the test-network.
 * (e.g., /EHR/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json)
 */
const CCP_PATH = path.resolve(
  __dirname, // server/fabric
  '..', // server
  '..', // EHR (root)
  'fabric-samples',
  'test-network',
  'organizations',
  'peerOrganizations',
  'org1.example.com',
  'connection-org1.json'
);

// --- Fabric Constants ---
const CHANNEL_NAME = 'ehrchannel';
const CHAINCODE_NAME = 'ehr';
const MSP_ID = 'Org1MSP';

/**
 * The identity name to use for connecting to the network.
 * This identity must be enrolled and exist in your WALLET_PATH.
 * You typically create this using the 'registerUser.js' script.
 */
const IDENTITY_NAME = 'appUser';

const ORG1_USER_CERT_PATH = path.resolve(
  __dirname,
  '..',
  '..',
  'fabric-samples',
  'test-network',
  'organizations',
  'peerOrganizations',
  'org1.example.com',
  'users',
  'User1@org1.example.com',
  'msp',
  'signcerts',
  'cert.pem'
);

const ORG1_USER_KEY_DIR = path.resolve(
  __dirname,
  '..',
  '..',
  'fabric-samples',
  'test-network',
  'organizations',
  'peerOrganizations',
  'org1.example.com',
  'users',
  'User1@org1.example.com',
  'msp',
  'keystore'
);

function createMockTransactionId(functionName: string): string {
  return `local-${functionName}-${crypto.randomUUID()}`;
}

function readCurrentOrg1Identity(): { certificate: string; privateKey: string } {
  if (!fs.existsSync(ORG1_USER_CERT_PATH)) {
    throw new Error(
      `Fabric user certificate not found at ${ORG1_USER_CERT_PATH}. Start the test network and enroll Org1 users first.`
    );
  }

  if (!fs.existsSync(ORG1_USER_KEY_DIR)) {
    throw new Error(
      `Fabric user keystore not found at ${ORG1_USER_KEY_DIR}. Start the test network and enroll Org1 users first.`
    );
  }

  const certificate = fs.readFileSync(ORG1_USER_CERT_PATH, 'utf8');
  const keyFiles = fs.readdirSync(ORG1_USER_KEY_DIR);
  const keyFile = keyFiles.find((file) => file.endsWith('_sk'));

  if (!keyFile) {
    throw new Error(`No private key ending with '_sk' found in ${ORG1_USER_KEY_DIR}.`);
  }

  const privateKey = fs.readFileSync(path.join(ORG1_USER_KEY_DIR, keyFile), 'utf8');
  return { certificate, privateKey };
}

function isX509Identity(identity: Identity | undefined): identity is X509Identity {
  return !!identity && identity.type === 'X.509';
}

async function ensureWalletIdentity(wallet: Wallet): Promise<void> {
  const currentIdentity = readCurrentOrg1Identity();
  const existingIdentity = await wallet.get(IDENTITY_NAME);

  const existingCertificate = isX509Identity(existingIdentity)
    ? existingIdentity.credentials.certificate
    : undefined;

  const existingPrivateKey = isX509Identity(existingIdentity)
    ? existingIdentity.credentials.privateKey
    : undefined;

  const identityChanged =
    !existingIdentity ||
    existingIdentity.mspId !== MSP_ID ||
    existingCertificate !== currentIdentity.certificate ||
    existingPrivateKey !== currentIdentity.privateKey;

  if (!identityChanged) {
    return;
  }

  const walletIdentity: X509Identity = {
    credentials: currentIdentity,
    mspId: MSP_ID,
    type: 'X.509',
  };

  await wallet.put(IDENTITY_NAME, walletIdentity);

  console.log(
    existingIdentity
      ? `Refreshed stale wallet identity '${IDENTITY_NAME}' from current Org1 user credentials.`
      : `Imported wallet identity '${IDENTITY_NAME}' from current Org1 user credentials.`
  );
}

// --- Internal Function ---

/**
 * Connects to the Fabric gateway and returns the contract and gateway objects.
 * This function is used by both submit and evaluate.
 */
async function connectToGateway(): Promise<{ contract: Contract; gateway: Gateway }> {
  // 1. Load the wallet
  const wallet: Wallet = await Wallets.newFileSystemWallet(WALLET_PATH);
  console.log(`Wallet path: ${WALLET_PATH}`);

  // Keep the local test-network wallet aligned with the current Org1 user.
  await ensureWalletIdentity(wallet);

  // 2. Check if the identity exists
  const identity = await wallet.get(IDENTITY_NAME);
  if (!identity) {
    console.error(`Identity '${IDENTITY_NAME}' not found in wallet.`);
    console.error('Please run the registerUser.js script before starting the server.');
    throw new Error(`Identity '${IDENTITY_NAME}' not found.`);
  }

  // 3. Load the connection profile (CCP)
  const ccpRaw = fs.readFileSync(CCP_PATH, 'utf8');
  const ccp = JSON.parse(ccpRaw);

  // 4. Set up gateway connection options
  const gatewayOptions: GatewayOptions = {
    wallet,
    identity: IDENTITY_NAME,
    discovery: { enabled: true, asLocalhost: true }, // Use discovery service
  };

  // 5. Connect to the gateway
  const gateway = new Gateway();
  try {
    await gateway.connect(ccp, gatewayOptions);
    console.log('Connected to Fabric gateway.');

    // 6. Get the network (channel)
    const network = await gateway.getNetwork(CHANNEL_NAME);

    // 7. Get the contract (chaincode)
    const contract = network.getContract(CHAINCODE_NAME);
    console.log(`Using chaincode '${CHAINCODE_NAME}' on channel '${CHANNEL_NAME}'.`);

    return { contract, gateway };
  } catch (error) {
    // Disconnect on connection failure
    gateway.disconnect();
    console.error('Failed to connect to gateway:', error);
    if (error instanceof Error && error.message.includes('access denied')) {
      console.error(
        `Fabric discovery for channel '${CHANNEL_NAME}' was denied. Verify that '${IDENTITY_NAME}' belongs to the current Org1 network and that '${CHANNEL_NAME}' exists on the running peers.`
      );
    }
    throw error;
  }
}

// --- Core Transaction Functions (Internal) ---

/**
 * Submits a transaction to the ledger (for Create, Update, Delete operations).
 * @param functionName - The chaincode function to call (e.g., 'createEHR').
 * @param args - The arguments to pass to the chaincode function.
 * @returns The result from the chaincode, typically a stringified object.
 */
async function submitTransaction(functionName: string, ...args: string[]): Promise<string> {
  if (!USE_FABRIC) {
    const txId = createMockTransactionId(functionName);
    console.log(
      `[fabric disabled] Skipping submitTransaction('${functionName}') with args: ${args.join(', ')}. Generated txId: ${txId}`
    );
    return txId;
  }

  let gateway: Gateway | undefined;
  try {
    // Connect and get the contract
    const connectResult = await connectToGateway();
    gateway = connectResult.gateway; // Get the gateway to disconnect in finally
    const contract = connectResult.contract;

    // Submit the transaction
    console.log(`--> Submitting Transaction: ${functionName} with args: ${args.join(', ')}`);
    const resultBuffer = await contract.submitTransaction(functionName, ...args);

    // Process and return the result
    const result = resultBuffer.toString();
    console.log('--> Transaction submitted successfully. Result:', result);
    return result;
  } catch (error) {
    console.error(`Failed to submit transaction: ${error}`);
    throw error; // Re-throw for your API controller to catch
  } finally {
    // Always disconnect the gateway
    if (gateway) {
      gateway.disconnect();
      console.log('Gateway disconnected.');
    }
  }
}

/**
 * Evaluates a query on the ledger (for Read operations).
 * @param functionName - The chaincode function to call (e.g., 'readEHR').
 * @param args - The arguments to pass to the chaincode function.
 * @returns The result from the chaincode, typically a stringified JSON object.
 */
async function evaluateTransaction(functionName: string, ...args: string[]): Promise<string> {
  if (!USE_FABRIC) {
    console.log(
      `[fabric disabled] Skipping evaluateTransaction('${functionName}') with args: ${args.join(', ')}.`
    );
    return JSON.stringify({
      mode: 'database-only',
      fabricEnabled: false,
      functionName,
      args,
    });
  }

  let gateway: Gateway | undefined;
  try {
    // Connect and get the contract
    const connectResult = await connectToGateway();
    gateway = connectResult.gateway; // Get the gateway to disconnect in finally
    const contract = connectResult.contract;

    // Evaluate the transaction (read-only query)
    console.log(`--> Evaluating Query: ${functionName} with args: ${args.join(', ')}`);
    const resultBuffer = await contract.evaluateTransaction(functionName, ...args);

    // Process and return the result
    const result = resultBuffer.toString();
    console.log(`--> Query successful. Result: ${result}`);
    return result;
  } catch (error) {
    console.error(`Failed to evaluate transaction: ${error}`);
    throw error; // Re-throw for your API controller to catch
  } finally {
    // Always disconnect the gateway
    if (gateway) {
      gateway.disconnect();
      console.log('Gateway disconnected.');
    }
  }
}

// --- Utility and Wrapper Functions (Internal) ---
// These are the functions your routes.ts file expects.

/**
 * Creates a SHA-256 hash of any data.
 */
function hashData(data: any): string {
  const dataString = typeof data === 'string' ? data : JSON.stringify(data);
  return crypto.createHash('sha256').update(dataString).digest('hex');
}

/**
 * Wrapper for the 'addRecord' chaincode function.
 * Chaincode expects: (recordId, patientId, recordHash, doctorId, metadata)
 */
async function addRecord(patientId: string, dataHash: string, doctorId: string | null): Promise<string> {
  const doctorIdStr = doctorId || ''; // Pass empty string if null/undefined
  const recordId = crypto.randomUUID(); // generate a unique record id for ledger key
  const metadataStr = JSON.stringify({ createdBy: doctorIdStr || 'system', createdAt: new Date().toISOString() });
  return submitTransaction('addRecord', recordId, patientId, dataHash, doctorIdStr, metadataStr);
}

/**
 * Wrapper for the 'grantAccess' chaincode function.
 * Chaincode expects: (accessId, patientId, entityId, permissions)
 */
async function grantAccess(patientId: string, entityId: string, permissions: string[]): Promise<string> {
  const permissionsStr = JSON.stringify(permissions);
  const accessId = crypto.randomUUID();
  return submitTransaction('grantAccess', accessId, patientId, entityId, permissionsStr);
}

/**
 * Wrapper for the 'revokeAccess' chaincode function.
 * Chaincode expects: (accessId)
 * We'll accept (patientId, entityId) in caller code but here we require accessId.
 */
async function revokeAccess(accessId: string): Promise<string> {
  return submitTransaction('revokeAccess', accessId);
}

// --- Exported Service Object ---
// This is what your routes.ts file will import.

export const blockchainService = {
  submitTransaction,
  evaluateTransaction,
  hashData,
  addRecord,
  grantAccess,
  revokeAccess,
};
